# Generated by Django 5.2.13 on 2026-04-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
