# Generated by Django 5.2.13 on 2026-04-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
