# Generated by Django 5.2.13 on 2026-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_resident_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
