# Generated by Django 5.2.13 on 2026-04-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_blacklistedaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.TextField(unique=True),
        ),
    ]
