# Generated by Django 5.2.13 on 2026-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_resident_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.TextField(),
        ),
    ]
